### ISSUE TITLE
ffmpegthumbnailer doesn't match .mkv files

### ISSUE THREAD

**Issue by zaza42** [isene/RTFM#3]
Very short report + fix. :-> 
```
524c524
<     elsif @selected.match(/\.mpg$|\.mpeg$|\.avi$|\.mov$|\.mp4$/)
---
>     elsif @selected.match(/\.mpg$|\.mpeg$|\.avi$|\.mov$|\.mp4$|\.mkv$/)

```

**Comment by isene** [comment]
Hehe - it's already fixed in the code I have not yet committed :-) Coming soon - just want to get pager functionality for the right window to work before I commit.

**Comment by isene** [comment]
Fixed - and full pager functionality is now added.
